Fix the warning specified staticcheck
- internal/completion/
    - completion.go:334:16: do not pass a nil Context, even if a function permits it; pass context.TODO if you are unsure about which Context to use (SA1012)
    - env.go:57:6: should omit nil check; len() for []int is defined as zero (S1009)
- internal/frame/
    - coloring.go:48:2: this value of color is never used (SA4006)
    - option.go:49:6: func shellJoin is unused (U1000)
- internal/functions/
    - bindkey.go:14:9: readline.GlobalKeyMap.GetBindKey is deprecated: GetBindKey returns the function assigned to given key  (SA1019)
    - builtinfunc_windows.go:62:15: mbcs.AtoU is deprecated: use AnsiToUtf8  (SA1019)
    - builtinfunc_windows.go:76:14: mbcs.UtoA is deprecated: use Utf8ToAnsi  (SA1019)
- internal/alias
    - alias.go:13:5: var dbg is unused (U1000)
    - expand.go:18:7: should omit nil check; len() for []string is defined as zero (S1009)
    - expand.go:24:7: should omit nil check; len() for []string is defined as zero (S1009)
- internal/commands/
    - attrib_windows.go:69:31: should omit nil check; len() for []string is defined as zero (S1009)
    - cd.go:65:2: should replace this if statement with an unconditional strings.TrimPrefix (S1017)
    - chmod.go:17:10: error strings should not be capitalized (ST1005)
    - clip_windows.go:29:15: mbcs.AtoU is deprecated: use AnsiToUtf8  (SA1019)
    - kill.go:17:13: error strings should not be capitalized (ST1005)
    - kill.go:25:13: error strings should not be capitalized (ST1005)
    - kill.go:42:13: error strings should not be capitalized (ST1005)
    - lnk.go:68:3: redundant break statement (S1023)
    - lnk.go:73:3: redundant break statement (S1023)
    - lnk.go:78:3: redundant break statement (S1023)
    - ls_windows.go:400:5: should omit nil check; len() for []string is defined as zero (S1009)
    - mklink.go:28:14: error strings should not be capitalized (ST1005)
    - mklink.go:33:13: error strings should not be capitalized (ST1005)
    - seta.go:48:6: should use !strings.ContainsRune(" \t\v\r\n", ch) instead (S1003)
    - source.go:21:6: should omit nil check; len() for []string is defined as zero (S1009)
    - touch.go:12:19: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (S1007)
- internal/history
    - history.go:53:30: should use strings.ContainsRune(DisableMarks, ch) instead (S1003)
- internal/mains/
    - argsfilter.go:28:20: error strings should not be capitalized (ST1005)
    - bindkey.go:134:12: do not pass a nil Context, even if a function permits it; pass context.TODO if you are unsure about which Context to use (SA1012)
    - commandnotfound.go:19:10: error strings should not be capitalized (ST1005)
    - io.go:364:5: redundant break statement (S1023)
    - io.go:381:5: redundant break statement (S1023)
    - lua.go:98:21: unnecessary use of fmt.Sprintf (S1039)
    - lua.go:104:21: unnecessary use of fmt.Sprintf (S1039)
    - nyagos.go:68:15: error strings should not be capitalized (ST1005)
    - nyagos.go:80:10: error strings should not be capitalized (ST1005)
- internal/shell/
    - interpreter.go:487:15: error strings should not be capitalized (ST1005)
    - interpreter.go:513:17: error strings should not be capitalized (ST1005)
    - loop.go:32:5: should omit nil check; len() for []string is defined as zero (S1009)
    - parser.go:23:9: should use strings.ContainsRune(" \t\n\r\v\f", c) instead (S1003)
    - parser.go:56:17: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (S1007)
    - parser.go:126:6: func chomp is unused (U1000)
- internal/texts/
     - split.go:9:5: var rxDoubleQuoted is unused (U1000)